-- liquibase formatted sql

-- changeset smakarenko:1

CREATE TABLE user_entity (
	id int4 generated by default as identity,
	first_name varchar(255) not NULL,
	last_name varchar(255) not NULL,
	password varchar(255),
	user_role varchar(255),
	primary key (id)

);

CREATE TABLE request_entity (
	id int4 generated by default as identity,
	request_status varchar(255),
	user_text varchar(64) not NULL,
	phone_number varchar(255) not NULL
	author_id int4 not NULL
	local_date_time timestamp NOT NULL,
	primary key (id)
);
